#!/usr/bin/env python3
"""Author the rock/scissors/paper gestures as pixel art with a real alpha channel.

The official AI Passport frames could not be reused: their hand and their radial
burst share one hue ramp with no separable boundary, so every mask attempt either
kept the dark burst (the black disc the UI showed) or ate part of the hand. These
sprites are drawn here instead, so transparency is authored rather than derived --
no colour keying is involved at any point.

Output: 16x16 tiles scaled 3x to 48x48 ARGB8888 PNG plus LVGL C arrays.
"""
import argparse
import subprocess
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "main" / "assets" / "rps_gestures"
LVGL_IMAGE = ROOT / "managed_components" / "lvgl__lvgl" / "scripts" / "LVGLImage.py"
SCALE = 3
CARD_BG = (0x17, 0x26, 0x3B, 255)

PALETTE = {
    ".": (0, 0, 0, 0),
    "O": (38, 26, 20, 255),     # outline
    "S": (247, 203, 158, 255),  # skin base
    "H": (255, 232, 202, 255),  # lit edge
    "D": (206, 146, 101, 255),  # shade / crease
}

ROCK = """
................
....OOOOOO......
...OHHHSSSO.....
..OHSSSSSSSO....
.OHSSSSSSSSSO...
.OSSSSSSSSSSO...
OSSDSSSSSSSSO...
OSSSDDDDDDSSO...
OSSSSSSSSSSSO...
OSSSSSSSSSSSO...
.OSSDDDDDDSSO...
.OSSSSSSSSSSO...
..OSSSSSSSSO....
...OOOOOOOO.....
................
................
"""

SCISSORS = """
................
...OO....OO.....
..OHSO..OSHO....
..OHSO..OSSO....
..OHSO.OSSO.....
..OHSO.OSSO.....
..OHSOOSSO......
..OHSSSSSO......
.OHSSSSSSSO.....
.OHSSSSSSSSO....
.OSSDDDDSSSO....
.OSSSSSSSSSO....
..OSSSSSSSO.....
...OOOOOOO......
................
................
"""

PAPER = """
................
..O.O.O.O.......
.OHOSOSOSO......
.OHOSOSOSO..OO..
.OHOSOSOSO.OSSO.
.OHOSOSOSO.OSSO.
.OHSSSSSSSOSSO..
.OHSSSSSSSSSSO..
OHSSSSSSSSSSO...
OHSSDDDDSSSSO...
OHSSSSSSSSSSO...
.OHSSSSSSSSO....
..OSSSSSSSO.....
...OOOOOOO......
................
................
"""

GESTURES = {"rock": ROCK, "scissors": SCISSORS, "paper": PAPER}


def tile(art):
    rows = [line for line in art.strip("\n").split("\n") if line]
    if len(rows) != 16 or any(len(row) != 16 for row in rows):
        raise SystemExit(f"gesture art must be 16x16, got {len(rows)} rows")
    image = Image.new("RGBA", (16, 16), (0, 0, 0, 0))
    pixels = image.load()
    for y, row in enumerate(rows):
        for x, char in enumerate(row):
            if char not in PALETTE:
                raise SystemExit(f"unknown palette char {char!r}")
            pixels[x, y] = PALETTE[char]
    return image


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--preview", type=Path, help="write a KP_CARD-backed preview sheet")
    parser.add_argument("--no-convert", action="store_true")
    args = parser.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    size = 16 * SCALE
    sheet = Image.new("RGBA", (size * len(GESTURES), size), CARD_BG)
    for index, (name, art) in enumerate(GESTURES.items()):
        sprite = tile(art).resize((size, size), Image.Resampling.NEAREST)
        png = OUT / f"rps_gesture_{name}.png"
        sprite.save(png, optimize=True)
        opaque = sum(1 for pixel in sprite.getdata() if pixel[3] > 0)
        print(f"{name}: {size}x{size} opaque={opaque} transparent={size * size - opaque} -> {png.name}")
        sheet.alpha_composite(sprite, (index * size, 0))
        if not args.no_convert:
            subprocess.run([
                "python3", str(LVGL_IMAGE), "--ofmt", "C", "--cf", "ARGB8888",
                "--compress", "NONE", "--output", str(OUT), str(png),
            ], check=True)
    if args.preview:
        sheet.convert("RGB").resize((sheet.width * 5, sheet.height * 5),
                                    Image.Resampling.NEAREST).save(args.preview)
        print(f"preview -> {args.preview}")


if __name__ == "__main__":
    main()
